Added drawBitmap
leaphy-robotics/leaphy-blockly pull request #260
Opened 2022-12-03 14:03 UTC by koen1711

**Didn't compile it for arduino_compressed!**

2022-12-03 14:04 UTC, koen1711 commented
Didn't compile the stuff I added.

2023-01-17 07:22 UTC, paulsiersma requested changes
A couple of things to check.

2023-01-17 07:22 UTC, paulsiersma commented on .gitignore
> +yarn.lock
yarn.lock is added twice.

2023-01-17 07:22 UTC, paulsiersma commented on demos/code/index.html
> +
I think removing this was a mistake, please revert

2023-01-17 07:22 UTC, paulsiersma commented on generators/arduino/leaphy_extra.js
> +//function GenerateBitmap(path) {
Please remove commented code

2023-01-17 07:22 UTC, paulsiersma commented on msg/messages.js
>  Blockly.Msg.LEAPHY_DISPLAY_DISPLAY = 'Show on display';
```suggestion
/** @type {string} */
/// Draw Bitmap
Blockly.Msg.LEAPHY_DRAW_BITMAP = 'Display %1 %2 %3 %4';
/** @type {string} */
/// Print display
Blockly.Msg.LEAPHY_DISPLAY_DISPLAY = 'Show on display';
```

2023-11-11 20:32 UTC, closed without merging